Repository PaloAltoNetworks/docusaurus-openapi-docs, pull requests merged in 2022-11, with the labels that each got.

#318 [Cleanup]: Remove "lorem ipsum" instances and boilerplate docs
  demo/docs/tutorial-basics/_category_.json
  demo/docs/tutorial-basics/congratulations.md
  demo/docs/tutorial-basics/create-a-blog-post.md
  demo/docs/tutorial-basics/create-a-document.md
  demo/docs/tutorial-basics/create-a-page.md
  demo/docs/tutorial-basics/deploy-your-site.md
  demo/docs/tutorial-basics/markdown-features.mdx
  demo/docs/tutorial-extras/_category_.json
  demo/docs/tutorial-extras/manage-docs-versions.md
  demo/docs/tutorial-extras/translate-your-site.md
  demo/examples/petstore-1.0.0.yaml
  demo/examples/petstore.yaml
Labels: enhancement

#320 [Bug] Use find instead of include to match tags
  packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts
Labels: bug

#321 [Bug] Check if plugin is array before accessing first index
  packages/docusaurus-plugin-openapi-docs/src/index.ts
Labels: bug

#322 [Bug] SchemaTabs arrows not rendering for response examples
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/index.js
Labels: bug

#325 [Bug] Improve support for multiline descriptions in frontmatter
  packages/docusaurus-plugin-openapi-docs/src/index.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
Labels: bug

#331 [Bug] Prevent ApiDemoPanel collapse for invalid requests
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Execute/index.tsx
Labels: bug, DO NOT MERGE

#336 [Bug] Introduce Docusaurus v2.2.0 support
  .github/workflows/build-perf.yml
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/src/index.ts
  packages/docusaurus-theme-openapi-docs/src/theme-classic.d.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Content/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Footer/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Footer/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Metadata/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Paginator/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/TOC/Desktop/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/TOC/Mobile/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/TOC/Mobile/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/styles.css
  yarn.lock
Labels: bug

#344 [Bug] Add condition for handling arrays of discriminators
  packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts
  packages/docusaurus-theme-openapi-docs/src/theme/DiscriminatorTabs/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/styles.css
Labels: bug
