Repository PaloAltoNetworks/docusaurus-openapi-docs, pull requests merged in 2022-05, with the labels that each got.

#68 Update README with usage
  README.md
  packages/docusaurus-plugin-openapi/README.md
Labels: documentation, DO NOT MERGE

#72 [Spring Cleaning] Update READMES with Configuration Options table
  README.md
  packages/docusaurus-plugin-openapi-docs/README.md
Labels: documentation

#74 [Packaging] Add package.json keywords and update git URL
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
Labels: documentation

#76 [Fix Breaking Change] Pin to docusaurus 2.0.0-beta.18
  README.md
  demo/package.json
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
Labels: bug, documentation, DO NOT MERGE

#84 [Theme]: Fix @theme/Tabs namespace collision
  demo/api/cos/create-a-bucket.api.mdx
  demo/api/cos/generating-an-iam-token.api.mdx
  demo/api/cos/list-buckets.api.mdx
  demo/api/cos/retrieve-a-buckets-headers.api.mdx
  demo/api/food/burgers/list-all-burgers.api.mdx
  demo/api/food/yogurtstore/list-all-flavors.api.mdx
  demo/api/openapi-issue/missing-summary.api.mdx
  demo/api/petstore/add-a-new-pet-to-the-store.api.mdx
  demo/api/petstore/create-user.api.mdx
  demo/api/petstore/creates-list-of-users-with-given-input-array.api.mdx
  demo/api/petstore/delete-purchase-order-by-id.api.mdx
  demo/api/petstore/delete-user.api.mdx
  demo/api/petstore/deletes-a-pet.api.mdx
  demo/api/petstore/find-pet-by-id.api.mdx
  demo/api/petstore/find-purchase-order-by-id.api.mdx
  demo/api/petstore/finds-pets-by-status.api.mdx
  demo/api/petstore/finds-pets-by-tags.api.mdx
  demo/api/petstore/get-user-by-user-name.api.mdx
  demo/api/petstore/logs-out-current-logged-in-user-session.api.mdx
  demo/api/petstore/logs-user-into-the-system.api.mdx
  demo/api/petstore/place-an-order-for-a-pet.api.mdx
  demo/api/petstore/returns-pet-inventories-by-status.api.mdx
  demo/api/petstore/subscribe-to-the-store-events.api.mdx
  demo/api/petstore/update-an-existing-pet.api.mdx
  demo/api/petstore/updated-user.api.mdx
  demo/api/petstore/updates-a-pet-in-the-store-with-form-data.api.mdx
  demo/api/petstore/uploads-an-image.api.mdx
  packages/docusaurus-plugin-openapi-docs/src/markdown/createStatusCodes.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/styles.module.css
Labels: bug

#86 [Bug]: TypeError: Cannot read properties of undefined (reading 'schema')
  packages/docusaurus-plugin-openapi-docs/src/markdown/createSchemaDetails.ts
Labels: bug

#93 [FR] Added security schemes support for SecuritySchemes component
  packages/docusaurus-plugin-openapi-docs/src/openapi/types.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Authorization/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Execute/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Execute/makeRequest.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/SecuritySchemes/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/buildPostmanRequest.ts
Labels: enhancement

#96 [FR] Additional supported fields for index.api.mdx
  demo/api/petstore/index.api.mdx
  packages/docusaurus-plugin-openapi-docs/src/markdown/createContactInfo.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createFullWidthTable.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createLicense.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createParamsTable.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestBodyTable.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createSchemaTable.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createTermsOfService.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
Labels: enhancement, DO NOT MERGE

#97 [Enhancement] Improve category link support when grouping by tags
  demo/api/food/burgers/burger-example.info.mdx
  demo/api/food/yogurtstore/frozen-yogurt-example.info.mdx
  demo/api/petstore/sidebar.js
  demo/api/petstore/swagger-petstore-yaml.info.mdx
  demo/examples/cspm/AccessKeys.yaml
  demo/examples/cspm/AccountGroups.yaml
  demo/examples/cspm/AdoptionAdvisor.yaml
  demo/examples/cspm/AlertRules.yaml
  demo/examples/cspm/Alerts.yaml
  demo/examples/cspm/AnomalySettings.yaml
  demo/examples/cspm/AnomalyTrustedList.yaml
  demo/examples/cspm/AssetInventory.yaml
  demo/examples/cspm/AuditLogs.yaml
  demo/examples/cspm/CloudAccounts.yaml
  demo/examples/cspm/CompliancePosture.yaml
  demo/examples/cspm/ComplianceStandards.yaml
  demo/examples/cspm/DataSecurityDashboard.yaml
  demo/examples/cspm/DataSecurityInventory.yaml
  demo/examples/cspm/DataSecuritySettings.yaml
  demo/examples/cspm/IAM.yaml
  demo/examples/cspm/IAMIdp.yaml
  demo/examples/cspm/IPAllowList.yaml
  demo/examples/cspm/IacScan.yaml
  demo/examples/cspm/Integrations.yaml
  demo/examples/cspm/IntegrationsPull.yaml
  demo/examples/cspm/LicensingV2.yaml
  demo/examples/cspm/Login.yaml
  demo/examples/cspm/NotificationTemplates.yaml
  demo/examples/cspm/Policy.yaml
  demo/examples/cspm/Reports.yaml
  demo/examples/cspm/ResourceExplorer.yaml
  demo/examples/cspm/ResourceLists.yaml
  demo/examples/cspm/Search.yaml
  demo/examples/cspm/SearchManager.yaml
  demo/examples/cspm/Settings.yaml
  demo/examples/cspm/System.yaml
  demo/examples/cspm/UserProfile.yaml
  demo/examples/cspm/UserRoles.yaml
  demo/examples/cspm/sidebar.js
  packages/docusaurus-plugin-openapi-docs/src/index.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/types.ts
  packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts
  packages/docusaurus-plugin-openapi-docs/src/types.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/styles.module.css
Labels: enhancement, DO NOT MERGE

#100 [Bug] Refactor categoryLinkSource option and usage
  packages/docusaurus-plugin-openapi-docs/src/index.ts
  packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts
  packages/docusaurus-plugin-openapi-docs/src/types.ts
Labels: bug

#101 [Documentation] Add categoryLinkSource to usage
  README.md
  packages/docusaurus-plugin-openapi-docs/README.md
Labels: documentation
