Repository PaloAltoNetworks/docusaurus-openapi-docs, pull requests merged in 2022-07, with the labels that each got.

#147 Add await to resolveJsonRefs
  packages/docusaurus-plugin-openapi-docs/src/openapi/utils/loadAndBundleSpec.ts
Labels: bug

#149 [FR] ApiDemoPanel (a11y): Improve keyboard tab support
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/FloatingButton/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/FloatingButton/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/LiveEditor/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ParamOptions/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Server/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Server/styles.module.css
Labels: enhancement, DO NOT MERGE

#148 [Enhancement] Integrate ReDoc OpenAPIParser
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-plugin-openapi-docs/src/openapi/utils/services/OpenAPIParser.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/utils/services/RedocNormalizedOptions.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/utils/types/index.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/utils/types/open-api.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/utils/utils/JsonPointer.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/utils/utils/helpers.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/utils/utils/index.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/utils/utils/openapi.ts
  yarn.lock
Labels: enhancement

#159 [Bug] Check for basePath before defining intro and category link doc ids
  packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts
Labels: bug

#155 [Upgrade] Docusaurus Beta 22 support
  demo/package.json
  demo/src/css/custom.css
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Content/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Footer/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Footer/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/icons/bash-original.svg
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/icons/go-original-wordmark.svg
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/icons/javascript-original.svg
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/icons/linux-original.svg
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/icons/python-original.svg
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Metadata/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Paginator/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/TOC/Desktop/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/TOC/Mobile/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/TOC/Mobile/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/index.js
  yarn.lock
Labels: DO NOT MERGE

#160 [Bug Fix] SchemaTabs: Cannot read properties of undefined
  demo/docs/cos/create-a-bucket.api.mdx
  demo/docs/petstore/add-a-new-pet-to-the-store.api.mdx
  demo/docs/petstore/create-user.api.mdx
  demo/docs/petstore/creates-list-of-users-with-given-input-array.api.mdx
  demo/docs/petstore/creates-list-of-users-with-given-input-list.api.mdx
  demo/docs/petstore/find-pet-by-id.api.mdx
  demo/docs/petstore/find-purchase-order-by-id.api.mdx
  demo/docs/petstore/finds-pets-by-status.api.mdx
  demo/docs/petstore/finds-pets-by-tags.api.mdx
  demo/docs/petstore/get-user-by-user-name.api.mdx
  demo/docs/petstore/logs-user-into-the-system.api.mdx
  demo/docs/petstore/place-an-order-for-a-pet.api.mdx
  demo/docs/petstore/returns-pet-inventories-by-status.api.mdx
  demo/docs/petstore/update-an-existing-pet.api.mdx
  demo/docs/petstore/updated-user.api.mdx
  demo/docs/petstore/uploads-an-image.api.mdx
  demo/docs/petstore_versioned/1.0.0/add-a-new-pet-to-the-store.api.mdx
  demo/docs/petstore_versioned/1.0.0/create-user.api.mdx
  demo/docs/petstore_versioned/1.0.0/creates-list-of-users-with-given-input-array.api.mdx
  demo/docs/petstore_versioned/1.0.0/creates-list-of-users-with-given-input-list.api.mdx
  demo/docs/petstore_versioned/1.0.0/find-pet-by-id.api.mdx
  demo/docs/petstore_versioned/1.0.0/find-purchase-order-by-id.api.mdx
  demo/docs/petstore_versioned/1.0.0/finds-pets-by-status.api.mdx
  demo/docs/petstore_versioned/1.0.0/finds-pets-by-tags.api.mdx
  demo/docs/petstore_versioned/1.0.0/get-user-by-user-name.api.mdx
  demo/docs/petstore_versioned/1.0.0/logs-user-into-the-system.api.mdx
  demo/docs/petstore_versioned/1.0.0/place-an-order-for-a-pet.api.mdx
  demo/docs/petstore_versioned/1.0.0/returns-pet-inventories-by-status.api.mdx
  demo/docs/petstore_versioned/1.0.0/update-an-existing-pet.api.mdx
  demo/docs/petstore_versioned/1.0.0/updated-user.api.mdx
  demo/docs/petstore_versioned/1.0.0/uploads-an-image.api.mdx
  demo/docs/petstore_versioned/add-a-new-pet-to-the-store.api.mdx
  demo/docs/petstore_versioned/create-user.api.mdx
  demo/docs/petstore_versioned/creates-list-of-users-with-given-input-array.api.mdx
  demo/docs/petstore_versioned/creates-list-of-users-with-given-input-list.api.mdx
  demo/docs/petstore_versioned/find-pet-by-id.api.mdx
  demo/docs/petstore_versioned/find-purchase-order-by-id.api.mdx
  demo/docs/petstore_versioned/finds-pets-by-status.api.mdx
  demo/docs/petstore_versioned/finds-pets-by-tags.api.mdx
  demo/docs/petstore_versioned/get-user-by-user-name.api.mdx
  demo/docs/petstore_versioned/logs-user-into-the-system.api.mdx
  demo/docs/petstore_versioned/place-an-order-for-a-pet.api.mdx
  demo/docs/petstore_versioned/returns-pet-inventories-by-status.api.mdx
  demo/docs/petstore_versioned/update-an-existing-pet.api.mdx
  demo/docs/petstore_versioned/updated-user.api.mdx
  demo/docs/petstore_versioned/uploads-an-image.api.mdx
  packages/docusaurus-plugin-openapi-docs/src/markdown/createAnyOneOf.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createSchemaDetails.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/schema.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/types.ts
Labels: bug

#171 [FR] Add support for Response Headers
  packages/docusaurus-plugin-openapi-docs/src/markdown/createStatusCodes.ts
Labels: enhancement
