Repository PaloAltoNetworks/docusaurus-openapi-docs, pull requests merged in 2022-09, with the labels that each got.

#235 [Enhancement] Expand supported CodeTab languages
  demo/docusaurus.config.js
  packages/docusaurus-theme-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Curl/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Curl/languages.json
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/icons/bash-original.svg
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/icons/go-original-wordmark.svg
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/icons/javascript-original.svg
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/icons/linux-original.svg
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/icons/python-original.svg
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/Layout/styles.module.css
  yarn.lock
Labels: enhancement

#239 [Bug] Fix support for markdown template
  demo/api.mustache
  demo/docs/petstore/add-pet.api.mdx
  demo/docs/petstore/create-user.api.mdx
  demo/docs/petstore/create-users-with-array-input.api.mdx
  demo/docs/petstore/create-users-with-list-input.api.mdx
  demo/docs/petstore/delete-order.api.mdx
  demo/docs/petstore/delete-pet.api.mdx
  demo/docs/petstore/delete-user.api.mdx
  demo/docs/petstore/find-pets-by-status.api.mdx
  demo/docs/petstore/find-pets-by-tags.api.mdx
  demo/docs/petstore/get-inventory.api.mdx
  demo/docs/petstore/get-order-by-id.api.mdx
  demo/docs/petstore/get-pet-by-id.api.mdx
  demo/docs/petstore/get-user-by-name.api.mdx
  demo/docs/petstore/login-user.api.mdx
  demo/docs/petstore/logout-user.api.mdx
  demo/docs/petstore/pet.tag.mdx
  demo/docs/petstore/place-order.api.mdx
  demo/docs/petstore/store.tag.mdx
  demo/docs/petstore/subscribe-to-the-store-events.api.mdx
  demo/docs/petstore/swagger-petstore-yaml.info.mdx
  demo/docs/petstore/update-pet-with-form.api.mdx
  demo/docs/petstore/update-pet.api.mdx
  demo/docs/petstore/update-user.api.mdx
  demo/docs/petstore/upload-file.api.mdx
  demo/docs/petstore/user.tag.mdx
  demo/docs/petstore_versioned/1.0.0/get-order-by-id.api.mdx
  demo/docs/petstore_versioned/1.0.0/pet.tag.mdx
  demo/docs/petstore_versioned/1.0.0/place-order.api.mdx
  demo/docs/petstore_versioned/1.0.0/store.tag.mdx
  demo/docs/petstore_versioned/1.0.0/user.tag.mdx
  demo/docs/petstore_versioned/get-order-by-id.api.mdx
  demo/docs/petstore_versioned/pet.tag.mdx
  demo/docs/petstore_versioned/place-order.api.mdx
  demo/docs/petstore_versioned/store.tag.mdx
  demo/docs/petstore_versioned/user.tag.mdx
  demo/docusaurus.config.js
  packages/docusaurus-plugin-openapi-docs/src/index.ts
Labels: bug, enhancement

#238 Fix missing array opening bracket.
  README.md
Labels: documentation

#244 [Experimental] Adds multi-instance support to plugin CLI
  packages/docusaurus-plugin-openapi-docs/src/index.ts
Labels: enhancement, DO NOT MERGE

#247 [Bug] Fix logic that determines if an object property is required
  packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
Labels: bug

#248 [UI] Fix Schema Tabs arrow render
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/styles.module.css
Labels: bug

#251 [Bug] Delete writeOnly props instead of readOnly and ignore example if present
  demo/docs/petstore/find-pets-by-status.api.mdx
  demo/docs/petstore/find-pets-by-tags.api.mdx
  demo/docs/petstore/get-order-by-id.api.mdx
  demo/docs/petstore/get-pet-by-id.api.mdx
  demo/docs/petstore/get-user-by-name.api.mdx
  demo/docs/petstore/place-order.api.mdx
  demo/docs/petstore/subscribe-to-the-store-events.api.mdx
  demo/docs/petstore_versioned/1.0.0/find-pets-by-status.api.mdx
  demo/docs/petstore_versioned/1.0.0/find-pets-by-tags.api.mdx
  demo/docs/petstore_versioned/1.0.0/get-order-by-id.api.mdx
  demo/docs/petstore_versioned/1.0.0/get-pet-by-id.api.mdx
  demo/docs/petstore_versioned/1.0.0/get-user-by-name.api.mdx
  demo/docs/petstore_versioned/1.0.0/place-order.api.mdx
  demo/docs/petstore_versioned/1.0.0/subscribe-to-the-store-events.api.mdx
  demo/docs/petstore_versioned/find-pets-by-status.api.mdx
  demo/docs/petstore_versioned/find-pets-by-tags.api.mdx
  demo/docs/petstore_versioned/get-order-by-id.api.mdx
  demo/docs/petstore_versioned/get-pet-by-id.api.mdx
  demo/docs/petstore_versioned/get-user-by-name.api.mdx
  demo/docs/petstore_versioned/place-order.api.mdx
  demo/docs/petstore_versioned/subscribe-to-the-store-events.api.mdx
  packages/docusaurus-plugin-openapi-docs/src/openapi/createResponseExample.ts
Labels: bug

#252 [Enhancement] Split placeholder by newline and add title for tooltip
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/FormTextInput/index.tsx
Labels: enhancement

#258 [Enhancement] Relax docusaurus dependencies and upgrade demo to v2.1.0
  demo/package.json
  demo/yarn.lock
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
  yarn.lock
Labels: enhancement

#274 [Bug] Throw exception when operationId and summary not defined
  packages/docusaurus-plugin-openapi-docs/src/index.ts
Labels: bug

#277 [Bug] Ensure correct docPath is resolved when pluginId is passed
  packages/docusaurus-plugin-openapi-docs/src/index.ts
Labels: bug

#281 [Enhancement] Increase contrast between active/non-active Schema/Response Tabs
  packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/styles.module.css
Labels: enhancement

#285 [Enhancement] Add support for rendering example `summary` as description
  demo/docs/petstore/get-order-by-id.api.mdx
  demo/docs/petstore/place-order.api.mdx
  demo/docs/petstore_versioned/1.0.0/get-order-by-id.api.mdx
  demo/docs/petstore_versioned/1.0.0/place-order.api.mdx
  demo/docs/petstore_versioned/get-order-by-id.api.mdx
  demo/docs/petstore_versioned/place-order.api.mdx
  packages/docusaurus-plugin-openapi-docs/src/markdown/createStatusCodes.ts
Labels: enhancement

#286 [Experimental] Move server input to request card
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/FloatingButton/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Request/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Request/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Server/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Server/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/index.tsx
Labels: enhancement
