Repository PaloAltoNetworks/docusaurus-openapi-docs, pull requests merged in 2022-06, with the labels that each got.

#114 [Enhancement] Use docs with embedded links as category link
  demo/docs/petstore/add-a-new-pet-to-the-store.api.mdx
  demo/docs/petstore/create-user.api.mdx
  demo/docs/petstore/creates-list-of-users-with-given-input-array.api.mdx
  demo/docs/petstore/creates-list-of-users-with-given-input-list.api.mdx
  demo/docs/petstore/delete-purchase-order-by-id.api.mdx
  demo/docs/petstore/delete-user.api.mdx
  demo/docs/petstore/deletes-a-pet.api.mdx
  demo/docs/petstore/find-pet-by-id.api.mdx
  demo/docs/petstore/find-purchase-order-by-id.api.mdx
  demo/docs/petstore/finds-pets-by-status.api.mdx
  demo/docs/petstore/finds-pets-by-tags.api.mdx
  demo/docs/petstore/get-user-by-user-name.api.mdx
  demo/docs/petstore/logs-out-current-logged-in-user-session.api.mdx
  demo/docs/petstore/logs-user-into-the-system.api.mdx
  demo/docs/petstore/pet.tag.mdx
  demo/docs/petstore/place-an-order-for-a-pet.api.mdx
  demo/docs/petstore/returns-pet-inventories-by-status.api.mdx
  demo/docs/petstore/sidebar.js
  demo/docs/petstore/store.tag.mdx
  demo/docs/petstore/subscribe-to-the-store-events.api.mdx
  demo/docs/petstore/swagger-petstore-yaml.info.mdx
  demo/docs/petstore/update-an-existing-pet.api.mdx
  demo/docs/petstore/updated-user.api.mdx
  demo/docs/petstore/updates-a-pet-in-the-store-with-form-data.api.mdx
  demo/docs/petstore/uploads-an-image.api.mdx
  demo/docs/petstore/user.tag.mdx
  packages/docusaurus-plugin-openapi-docs/src/index.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
  packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts
  packages/docusaurus-plugin-openapi-docs/src/types.ts
Labels: enhancement

#115 [Bug] Add try/catch to createExample to prevent TypeError
  packages/docusaurus-plugin-openapi-docs/src/openapi/createExample.ts
Labels: bug

#110 [Experimental] Info Docs: Added Authentication section with support for Security Schemes
  demo/docs/petstore/swagger-petstore-yaml.info.mdx
  packages/docusaurus-plugin-openapi-docs/src/index.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createAuthentication.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
  packages/docusaurus-plugin-openapi-docs/src/types.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/SecuritySchemes/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/index.tsx
  packages/docusaurus-theme-openapi-docs/src/types.ts
Labels: enhancement

#118 [Enhancement] Implement new OpenAPI parser
  demo/docs/openapi-issue/missing-summary.api.mdx
  demo/docs/petstore/add-a-new-pet-to-the-store.api.mdx
  demo/docs/petstore/create-user.api.mdx
  demo/docs/petstore/creates-list-of-users-with-given-input-array.api.mdx
  demo/docs/petstore/creates-list-of-users-with-given-input-list.api.mdx
  demo/docs/petstore/delete-purchase-order-by-id.api.mdx
  demo/docs/petstore/delete-user.api.mdx
  demo/docs/petstore/deletes-a-pet.api.mdx
  demo/docs/petstore/find-pet-by-id.api.mdx
  demo/docs/petstore/find-purchase-order-by-id.api.mdx
  demo/docs/petstore/finds-pets-by-status.api.mdx
  demo/docs/petstore/finds-pets-by-tags.api.mdx
  demo/docs/petstore/get-user-by-user-name.api.mdx
  demo/docs/petstore/logs-out-current-logged-in-user-session.api.mdx
  demo/docs/petstore/logs-user-into-the-system.api.mdx
  demo/docs/petstore/place-an-order-for-a-pet.api.mdx
  demo/docs/petstore/returns-pet-inventories-by-status.api.mdx
  demo/docs/petstore/subscribe-to-the-store-events.api.mdx
  demo/docs/petstore/update-an-existing-pet.api.mdx
  demo/docs/petstore/updated-user.api.mdx
  demo/docs/petstore/updates-a-pet-in-the-store-with-form-data.api.mdx
  demo/docs/petstore/uploads-an-image.api.mdx
  demo/docusaurus.config.js
  demo/examples/openapi-issue-21.json
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-plugin-openapi-docs/src/openapi/__fixtures__/examples/yogurtstore/_category_.json
  packages/docusaurus-plugin-openapi-docs/src/openapi/__fixtures__/examples/yogurtstore/froyo.yaml
  packages/docusaurus-plugin-openapi-docs/src/openapi/__fixtures__/examples/yogurtstore/nested/nested.yaml
  packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.test.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/utils/loadAndBundleSpec.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/utils/types.ts
  yarn.lock
Labels: bug, enhancement

#120 [Enhancement] Add support for URL specPath
  packages/docusaurus-plugin-openapi-docs/src/index.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
Labels: enhancement

#124 [Enhancement] Use plugin-content-docs path when generating sidebar doc items
  demo/docs/cos/create-a-bucket.api.mdx
  demo/docs/cos/generating-an-iam-token.api.mdx
  demo/docs/cos/list-buckets.api.mdx
  demo/docs/cos/retrieve-a-buckets-headers.api.mdx
  demo/docs/food/burgers/burger-example.info.mdx
  demo/docs/food/burgers/list-all-burgers.api.mdx
  demo/docs/food/yogurtstore/frozen-yogurt-example.info.mdx
  demo/docs/food/yogurtstore/list-all-flavors.api.mdx
  demo/docusaurus.config.js
  demo/sidebars.js
  packages/docusaurus-plugin-openapi-docs/src/index.ts
  packages/docusaurus-plugin-openapi-docs/src/options.ts
  packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts
  packages/docusaurus-plugin-openapi-docs/src/types.ts
Labels: enhancement

#134 [Bug] Re-introduce json-schema-ref-parser
  README.md
  demo/docs/intro.mdx
  demo/docusaurus.config.js
  packages/docusaurus-plugin-openapi-docs/README.md
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-plugin-openapi-docs/src/index.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.test.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/utils/loadAndBundleSpec.ts
  packages/docusaurus-plugin-openapi-docs/src/options.ts
  packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts
  packages/docusaurus-plugin-openapi-docs/src/types.ts
  yarn.lock
Labels: bug, enhancement

#137 [Documentation] Add sidebar and versioning docs
  demo/docs/intro.mdx
  demo/docs/sidebars.md
  demo/docs/versioning.md
  demo/sidebars.js
Labels: documentation
