Repository PaloAltoNetworks/docusaurus-openapi-docs, pull requests merged in 2022-04, with the labels that each got.

#42 [Hotfix]: Babel-loader import warnings
  packages/docusaurus-theme-openapi/src/markdown/createDescription.ts
  packages/docusaurus-theme-openapi/src/markdown/schema.ts
  packages/docusaurus-theme-openapi/src/markdown/utils.ts
  packages/docusaurus-theme-openapi/src/theme/ParamsItem/index.js
  packages/docusaurus-theme-openapi/src/theme/SchemaItem/index.js
  packages/docusaurus-theme-openapi/src/types.ts
Labels: DO NOT MERGE

#45 [Experimental] Enable prev/next for beforeApiDocs items
  packages/docusaurus-plugin-openapi/src/docs/docs.ts
  packages/docusaurus-plugin-openapi/src/index.ts
  packages/docusaurus-plugin-openapi/src/openapi/openapi.ts
Labels: enhancement

#49 [Bug] Fix mustache template
  packages/docusaurus-plugin-openapi/src/index.ts
Labels: bug

#51 [Workaround] Ensure info/index doc is first item in sidebar
  demo/api/cos/_category_.json
  demo/api/food/_category_.json
  demo/api/openapi-issue/_category_.json
  demo/api/petstore/_category_.json
  demo/apiSidebars.js
  packages/docusaurus-plugin-openapi/src/index.ts
Labels: enhancement

#52 [Styling]: Update css variables for ApiDemoPanel
  demo/src/css/custom.css
  packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/styles.module.css
Labels: enhancement

#57 [Cleanup]: Remove unused code
  demo/api/cos/create-a-bucket.api.mdx
  demo/api/cos/generating-an-iam-token.api.mdx
  demo/api/cos/list-buckets.api.mdx
  demo/api/cos/retrieve-a-buckets-headers.api.mdx
  demo/api/food/burgers/index.api.mdx
  demo/api/food/burgers/list-all-burgers.api.mdx
  demo/api/food/yogurtstore/index.api.mdx
  demo/api/food/yogurtstore/list-all-flavors.api.mdx
  demo/api/openapi-issue/missing-summary.api.mdx
  demo/api/petstore/add-a-new-pet-to-the-store.api.mdx
  demo/api/petstore/create-user.api.mdx
  demo/api/petstore/creates-list-of-users-with-given-input-array.api.mdx
  demo/api/petstore/delete-purchase-order-by-id.api.mdx
  demo/api/petstore/delete-user.api.mdx
  demo/api/petstore/deletes-a-pet.api.mdx
  demo/api/petstore/find-pet-by-id.api.mdx
  demo/api/petstore/find-purchase-order-by-id.api.mdx
  demo/api/petstore/finds-pets-by-status.api.mdx
  demo/api/petstore/finds-pets-by-tags.api.mdx
  demo/api/petstore/get-user-by-user-name.api.mdx
  demo/api/petstore/index.api.mdx
  demo/api/petstore/logs-out-current-logged-in-user-session.api.mdx
  demo/api/petstore/logs-user-into-the-system.api.mdx
  demo/api/petstore/place-an-order-for-a-pet.api.mdx
  demo/api/petstore/returns-pet-inventories-by-status.api.mdx
  demo/api/petstore/subscribe-to-the-store-events.api.mdx
  demo/api/petstore/update-an-existing-pet.api.mdx
  demo/api/petstore/updated-user.api.mdx
  demo/api/petstore/updates-a-pet-in-the-store-with-form-data.api.mdx
  demo/api/petstore/uploads-an-image.api.mdx
  demo/apiSidebars.js
  demo/docusaurus.config.js
  demo/package.json
  jest.config.js
  packages/docusaurus-plugin-openapi/src/index.ts
  packages/docusaurus-plugin-openapi/src/plugin-openapi.d.ts
  packages/docusaurus-plugin-openapi/src/types.ts
  packages/docusaurus-plugin-proxy/package.json
  packages/docusaurus-plugin-proxy/src/index.ts
  packages/docusaurus-plugin-proxy/src/options.ts
  packages/docusaurus-plugin-proxy/src/plugin-proxy.d.ts
  packages/docusaurus-plugin-proxy/src/types.ts
  packages/docusaurus-plugin-proxy/tsconfig.json
  packages/docusaurus-preset-openapi/README.md
  packages/docusaurus-preset-openapi/package.json
  packages/docusaurus-preset-openapi/src/index.ts
  packages/docusaurus-preset-openapi/src/preset-classic.d.ts
  packages/docusaurus-preset-openapi/src/preset-openapi.d.ts
  packages/docusaurus-preset-openapi/src/theme-translations.d.ts
  packages/docusaurus-preset-openapi/tsconfig.json
  packages/docusaurus-theme-openapi/src/theme/ApiDemoPanel/index.tsx
  yarn.lock
Labels: enhancement

#61 Prepare release v18.0.0-beta.1
  CHANGELOG.md
  demo/package.json
  lerna.json
  packages/create-docusaurus-openapi/package.json
  packages/docusaurus-plugin-openapi/package.json
  packages/docusaurus-template-openapi/package.json
  packages/docusaurus-theme-openapi/package.json
Labels: bug, enhancement

#65 Update CONTRIBUTING, SUPPORT, and CODE_OF_CONDUCT
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  SUPPORT.md
Labels: documentation
