Repository PaloAltoNetworks/docusaurus-openapi-docs, pull requests merged in 2023-05, with the labels that each got.

#561 [Bug] Add handler for oneOf properties, fix nested <li> and and avoid duplicate properties in createAnyOneOf
  packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/DiscriminatorTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/DiscriminatorTabs/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/MimeTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/styles.css
Labels: bug

#557 [UI Enhancement] Updated left doc panel styling
  packages/docusaurus-plugin-openapi-docs/src/markdown/createParamsDetails.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestHeader.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/FormItem/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/MethodEndpoint/_MethodEndpoint.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/MethodEndpoint/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Request/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiItem/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/_ApiTabs.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/DiscriminatorTabs/_DiscriminatorTabs.scss
  packages/docusaurus-theme-openapi-docs/src/theme/Markdown/Details/_Details.scss
  packages/docusaurus-theme-openapi-docs/src/theme/MimeTabs/_MimeTabs.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/_ParamsItem.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/_SchemaItem.scss
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/_SchemaTabs.scss
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/styles.scss
Labels: enhancement, v2.0.0

#567 Add optional `markdownGenerators` config option
  demo/docs/intro.mdx
  packages/docusaurus-plugin-openapi-docs/src/index.ts
  packages/docusaurus-plugin-openapi-docs/src/options.ts
  packages/docusaurus-plugin-openapi-docs/src/types.ts
Labels: documentation, enhancement

#569 Prepare release v1.7.3
  CHANGELOG.md
  demo/package.json
  lerna.json
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
Labels: bug, documentation, enhancement

#570 Prepare release v2.0.0-beta.3
  CHANGELOG.md
  demo/package.json
  lerna.json
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
Labels: bug, enhancement, v2.0.0

#573 [Bug] Use SchemaItem to render leaf discriminator properties/nodes
  packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts
Labels: bug, v2.0.0

#581 Include markdownGenerators docs in project and plugin READMEs
  README.md
  demo/docs/intro.mdx
  packages/docusaurus-plugin-openapi-docs/README.md
Labels: documentation
