Repository PaloAltoNetworks/docusaurus-openapi-docs, pull requests merged in 2023-03, with the labels that each got.

#468 Eval guard value as double not
  packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/utils.ts
  packages/docusaurus-theme-openapi-docs/src/markdown/utils.ts
Labels: bug

#465 Add support for rendering additionalProperties schemas
  packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts
Labels: bug

#470 Prepare release v1.6.1
  CHANGELOG.md
  demo/package.json
  lerna.json
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
Labels: bug, enhancement

#475 Add v2.0.0 branch to release workflows
  .github/workflows/pr-title-check.yaml
  .github/workflows/release.yaml
Labels: v2.0.0

#471 Prepare 2.3.0 support
  demo/package.json
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createStatusCodes.ts
  packages/docusaurus-theme-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Body/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/DiscriminatorTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/DiscriminatorTabs/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/MimeTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/MimeTabs/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/styles.css
  scripts/version.ts
  yarn.lock
Labels: v2.0.0

#479 Add `bold`, `svg` filtering and ensure parity between opening/closing regex
  packages/docusaurus-plugin-openapi-docs/src/markdown/utils.ts
Labels: bug

#476 [UI Enhancement] Refactor include status code in response
  demo/docusaurus.config.js
  packages/docusaurus-theme-openapi-docs/src/theme-openapi.d.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Execute/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Execute/makeRequest.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Response/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Response/slice.ts
  packages/docusaurus-theme-openapi-docs/src/theme/styles.css
Labels: v2.0.0

#481 Additional BEM/CSS cleanup
  packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Request/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Response/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/styles.scss
Labels: v2.0.0

#487 Prepare release v2.0.0-beta.1
  CHANGELOG.md
  demo/package.json
  lerna.json
  package.json
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
  scripts/changelog-beta.ts
Labels: v2.0.0

#489 [UI Enhancement] Restyle tree lines
  packages/docusaurus-theme-openapi-docs/src/theme/DiscriminatorTabs/_DiscriminatorTabs.scss
  packages/docusaurus-theme-openapi-docs/src/theme/Markdown/Details/_Details.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/_ParamsItem.scss
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/_SchemaItem.scss
  packages/docusaurus-theme-openapi-docs/src/theme/styles.scss
Labels: v2.0.0

#507 [Enhancement] Add support for powershell
  demo/docusaurus.config.js
  packages/docusaurus-theme-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Curl/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/styles.css
  yarn.lock
Labels: enhancement

#504 [Bug] Fix double scrollbars
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Curl/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Response/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/styles.css
Labels: bug

#517 [Bug] Add missing status/headers tabs and apply max-height to code
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Response/index.tsx
Labels: bug, v2.0.0

#515 Prepare release v2.0.0-beta.2
  CHANGELOG.md
  demo/package.json
  lerna.json
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
Labels: v2.0.0

#519 [Bug] Narrow SASS loader rules to avoid conflicts with docusaurus-plugin-sass
  packages/docusaurus-theme-openapi-docs/src/index.ts
Labels: bug, v2.0.0

#521 [Bug] Patch webpack sass loader
  packages/docusaurus-theme-openapi-docs/src/index.ts
Labels: bug, v2.0.0

#525 Update bash/curl logo and refactor how logo width/height are defined
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/_CodeTabs.scss
  packages/docusaurus-theme-openapi-docs/src/theme/styles.scss
Labels: v2.0.0
