Repository PaloAltoNetworks/docusaurus-openapi-docs, pull requests merged in 2023-04, with the labels that each got.

#527 [Enhancement] Add support for rendering vendor extensions
  README.md
  demo/api.mustache
  demo/docs/intro.mdx
  packages/docusaurus-plugin-openapi-docs/README.md
  packages/docusaurus-plugin-openapi-docs/src/index.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createVendorExtensions.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
  packages/docusaurus-plugin-openapi-docs/src/options.ts
  packages/docusaurus-plugin-openapi-docs/src/types.ts
Labels: enhancement

#531 [UI Enhancement] Move authorization card to ApiItem
  packages/docusaurus-plugin-openapi-docs/src/index.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createAuthorization.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/SecuritySchemes/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/Markdown/Details/_Details.scss
Labels: v2.0.0

#533 [UI Enhancement] Move CodeTabs above Request
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/_CodeTabs.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/index.tsx
Labels: v2.0.0

#537 [UI Enhancement] Add expand button to CodeBlock
  packages/docusaurus-theme-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/src/theme-openapi.d.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ApiCodeBlock/Container/_Container.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ApiCodeBlock/Container/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ApiCodeBlock/Content/Element.js
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ApiCodeBlock/Content/String.js
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ApiCodeBlock/Content/_Content.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ApiCodeBlock/CopyButton/_CopyButton.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ApiCodeBlock/CopyButton/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ApiCodeBlock/ExitButton/_ExitButton.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ApiCodeBlock/ExitButton/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ApiCodeBlock/ExpandButton/_ExpandButton.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ApiCodeBlock/ExpandButton/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ApiCodeBlock/Line/_Line.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ApiCodeBlock/Line/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ApiCodeBlock/WordWrapButton/_WordWrapButton.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ApiCodeBlock/WordWrapButton/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ApiCodeBlock/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/_CodeTabs.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Curl/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/styles.scss
  yarn.lock
Labels: v2.0.0

#540 [UI Enhancement] Restyle details markers with caret
  packages/docusaurus-theme-openapi-docs/src/theme/Markdown/Details/_Details.scss
Labels: v2.0.0

#541 Improve Algolia search for method endpoint paths
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/MethodEndpoint/index.tsx
Labels: enhancement

#542 [UI Enhancement] Response Examples: Updated styling and support for multiple language variants
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/_CodeTabs.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Curl/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/styles.scss
Labels: enhancement, v2.0.0

#551 Upgrade dependencies
  packages/docusaurus-plugin-openapi-docs/package.json
  yarn.lock
Labels: dependencies

#530 [UI Enhancement] Request form validation and updated styling
  packages/docusaurus-theme-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/src/theme-openapi.d.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ApiCodeBlock/Content/_Content.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Body/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/_CodeTabs.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/CodeTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Curl/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Execute/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/FormItem/_FormItem.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/FormItem/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/FormMultiSelect/_FormMultiSelect.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/FormMultiSelect/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/FormSelect/_FormSelect.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/FormTextInput/_FormTextInput.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/FormTextInput/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/LiveEditor/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ParamOptions/ParamFormItems/ParamArrayFormItem.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ParamOptions/ParamFormItems/ParamBooleanFormItem.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ParamOptions/ParamFormItems/ParamMultiSelectFormItem.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ParamOptions/ParamFormItems/ParamSelectFormItem.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ParamOptions/ParamFormItems/ParamTextFormItem.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ParamOptions/_ParamOptions.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/ParamOptions/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Request/_Request.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Request/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Request/makeRequest.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Response/_Response.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Response/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Server/_Server.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Server/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/_SchemaTabs.scss
  packages/docusaurus-theme-openapi-docs/src/theme/styles.scss
  yarn.lock
Labels: enhancement, v2.0.0

#553 [UI Enhancement] Enable Expand button for Response
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Response/index.tsx
Labels: v2.0.0

#554 Upgrade demo to 2.4.0 and update supported range in plugin and theme
  demo/package.json
  package.json
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
  yarn.lock
Labels: dependencies, v2.0.0
