Repository PaloAltoNetworks/docusaurus-openapi-docs, pull requests merged in 2023-02, with the labels that each got.

#397 [Bug] Support multiple same-level node types and improve items/array support
  demo/docusaurus.config.js
  demo/sidebars.js
  packages/docusaurus-plugin-openapi-docs/src/markdown/createArrayBracket.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createStatusCodes.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/createRequestExample.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/createResponseExample.ts
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/styles.module.css
  packages/docusaurus-theme-openapi-docs/src/theme/styles.css
Labels: bug

#400 Cleanup API doc demos
  demo/docusaurus.config.js
  demo/examples/petstore.yaml
  demo/sidebars.js
Labels: documentation

#406 [FR] Added support for summary and description for param schema examples
  packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/index.js
Labels: enhancement

#404 Add support for java and expand language variants
  demo/docs/customization/languagetabs.md
  demo/docusaurus.config.js
  packages/docusaurus-theme-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Curl/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/styles.css
  yarn.lock
Labels: enhancement

#420 Clarify support for OpenAPI 3.0
  README.md
  demo/docs/intro.mdx
Labels: documentation

#422 Implement NodePolyfillPlugin in theme webpack config
  packages/docusaurus-theme-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/src/index.ts
  yarn.lock
Labels: bug

#426 Fix logo/darkLogo and colorMode synching
  demo/examples/petstore-1.0.0.yaml
  demo/examples/petstore.yaml
  demo/static/img/petstore-logo-dark.png
  packages/docusaurus-theme-openapi-docs/src/theme/ApiLogo/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/styles.css
Labels: bug

#435 Remove trailing slash in outputDir option if present
  packages/docusaurus-plugin-openapi-docs/src/index.ts
  packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts
Labels: bug

#436 Improve handling of non-string default values
  packages/docusaurus-theme-openapi-docs/src/markdown/utils.ts
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/index.js
Labels: bug

#442 [bug] Use toString() utility to always convert example to string
  packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/index.js
Labels: bug

#446 Handle missing params/header schema
  demo/docusaurus.config.js
  packages/docusaurus-plugin-openapi-docs/src/markdown/createStatusCodes.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/index.js
Labels: enhancement

#444 Fix security schemes
  demo/examples/petstore.yaml
  packages/docusaurus-plugin-openapi-docs/src/markdown/createAuthentication.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/SecuritySchemes/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/styles.css
Labels: bug

#431 Convert title heading from h2 to h1 for better a11y
  demo/docusaurus.config.js
  packages/docusaurus-plugin-openapi-docs/src/markdown/createHeading.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
  packages/docusaurus-theme-openapi-docs/src/theme/styles.css
Labels: enhancement, v2.0.0

#452 Expand support for nullable objects and default to any for empty/unknown schemas
  packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts
Labels: bug

#455 Avoid falling back to MOD label when rendering oneOf/anyOf and title not defined
  demo/examples/petstore.yaml
  packages/docusaurus-plugin-openapi-docs/src/openapi/utils/loadAndResolveSpec.ts
Labels: bug

#456 [Enhancement] Add option to hide send button
  demo/api.mustache
  packages/docusaurus-plugin-openapi-docs/src/index.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
  packages/docusaurus-plugin-openapi-docs/src/options.ts
  packages/docusaurus-plugin-openapi-docs/src/types.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/Request/index.tsx
Labels: enhancement

#457 Add support for security vendor extensions
  demo/docusaurus.config.js
  packages/docusaurus-theme-openapi-docs/src/theme/ApiDemoPanel/SecuritySchemes/index.tsx
Labels: bug

#458 Prepare release v1.6.0
  CHANGELOG.md
  demo/package.json
  lerna.json
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
Labels: bug, enhancement, DO NOT MERGE

#459 Add code, thead and tbody to greaterThan regex
  packages/docusaurus-plugin-openapi-docs/src/markdown/utils.ts
Labels: bug

#463 Update options tables in READMEs and docs
  README.md
  demo/docs/intro.mdx
  packages/docusaurus-plugin-openapi-docs/README.md
Labels: documentation

#461 [FR] Add class to response tabs to differentiate success/error
  packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/styles.module.css
Labels: enhancement
