Repository PaloAltoNetworks/docusaurus-openapi-docs, pull requests merged in 2024-03, with the labels that each got.

#739 update compatibility matrix
  README.md
  demo/docs/intro.mdx
  packages/docusaurus-plugin-openapi-docs/README.md
Labels: documentation

#740 upgrade to docusaurus 3.1.1
  demo/package.json
  yarn.lock
Labels: v3.0.0

#741 Upgrade dependencies
  packages/docusaurus-plugin-openapi-docs/src/markdown/createAuthentication.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createCallbacks.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createContactInfo.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createLicense.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createLogo.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createParamsDetails.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestBodyDetails.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.test.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createStatusCodes.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/index.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/createRequestExample.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/createResponseExample.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/utils/loadAndResolveSpec.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/utils/services/OpenAPIParser.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/utils/utils/openapi.ts
  scripts/changelog-beta.ts
  scripts/changelog.ts
  scripts/check-pr-title.ts
  scripts/publish-beta.ts
  scripts/publish.ts
  yarn.lock
Labels: v2.0.0

#743 Prepare release v3.0.0-beta.6
  CHANGELOG.md
  README.md
  demo/docs/intro.mdx
  demo/package.json
  lerna.json
  packages/docusaurus-plugin-openapi-docs/README.md
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
Labels: v3.0.0

#744 Prepare release v2.1.0
  CHANGELOG.md
  README.md
  demo/docs/intro.mdx
  demo/package.json
  lerna.json
  packages/docusaurus-plugin-openapi-docs/README.md
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
Labels: v2.0.0

#748 Upgrade OpenAPI parsers
  packages/docusaurus-plugin-openapi-docs/package.json
  yarn.lock
Labels: v2.0.0

#749 Upgrade OpenAPI parsers
  packages/docusaurus-plugin-openapi-docs/package.json
  yarn.lock
Labels: v3.0.0

#756 Prepare release v2.1.1
  CHANGELOG.md
  demo/package.json
  lerna.json
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
Labels: v2.0.0

#757 Prepare release v3.0.0-beta.7
  CHANGELOG.md
  demo/package.json
  lerna.json
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
Labels: v3.0.0

#763 [bug] Ensure resize observer is calculated once per frame to avoid loops
  packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/DiscriminatorTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/MimeTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/OperationTabs/index.js
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/index.js
Labels: bug, v2.0.0

#764 Uncomment line preventing grouping by operation tags
  packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts
Labels: bug, v2.0.0

#765 Ensure qualifiers are rendered for polymorphic/primitive properties
  packages/docusaurus-plugin-openapi-docs/src/markdown/__snapshots__/createSchema.test.ts.snap
  packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts
Labels: bug, v2.0.0

#766 Fix allOf schema qualifier and type
  packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/schema.ts
Labels: bug, v2.0.0

#768 Prepare release v2.1.2
  CHANGELOG.md
  demo/package.json
  lerna.json
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
Labels: v2.0.0

#771 Ensure correct eval of required properties with nested allOf
  packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts
Labels: bug, v2.0.0

#772 Prepare release v2.1.3
  CHANGELOG.md
  demo/package.json
  lerna.json
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
Labels: bug, v2.0.0

#773 Prepare release v3.0.0-beta.9
  CHANGELOG.md
  demo/package.json
  lerna.json
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/index.tsx
Labels: v3.0.0

#778 upgrade lerna to 8.1.2
  lerna.json
  package.json
  yarn.lock
Labels: v3.0.0

#779 Use inline to remove p tag
  packages/docusaurus-plugin-openapi-docs/src/markdown/createVersionBadge.ts
Labels: bug, v3.0.0

#780 Prepare release v3.0.0-beta.10
  CHANGELOG.md
  demo/package.json
  lerna.json
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
Labels: v3.0.0

#785 [UI Bug Fix] Firefox issue: Hide empty scrollbar track from Tab components
  packages/docusaurus-theme-openapi-docs/src/theme/ApiTabs/_ApiTabs.scss
  packages/docusaurus-theme-openapi-docs/src/theme/DiscriminatorTabs/_DiscriminatorTabs.scss
  packages/docusaurus-theme-openapi-docs/src/theme/MimeTabs/_MimeTabs.scss
  packages/docusaurus-theme-openapi-docs/src/theme/OperationTabs/_OperationTabs.scss
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaTabs/_SchemaTabs.scss
Labels: bug
