Repository PaloAltoNetworks/docusaurus-openapi-docs, pull requests merged in 2024-06, with the labels that each got.

#847 Transparent background when displaying response placeholder
  packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/Response/index.tsx
Labels: bug, v3.0.0

#848 ensure readOnly/writeOnly are evaluated first
  packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts
Labels: v3.0.0

#849 Support empty object schemas
  packages/docusaurus-plugin-openapi-docs/src/markdown/createRequestSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createResponseSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts
Labels: enhancement, v3.0.0

#850 upgrade to docusaurus 3.4.0
  demo/package.json
  yarn.lock
Labels: enhancement, v3.0.0

#803 handle various additionalProperties cases
  packages/docusaurus-plugin-openapi-docs/src/markdown/__snapshots__/createSchema.test.ts.snap
  packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.test.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts
  packages/docusaurus-plugin-openapi-docs/src/openapi/types.ts
Labels: v3.0.0
