Repository PaloAltoNetworks/docusaurus-openapi-docs, pull requests merged in 2024-09, with the labels that each got.

#945 Expand language tab support
  demo/docusaurus.config.ts
  demo/src/css/custom.css
  packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeSnippets/code-snippets-types.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeSnippets/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeSnippets/languages.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeTabs/_CodeTabs.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeTabs/index.tsx
Labels: enhancement, v4.0.0

#949 Import MethodEndpoint hooks from @theme
  packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/MethodEndpoint/index.tsx
Labels: bug, v4.0.0

#952 Supporting merging all user defined languageTabs options
  demo/docs/customization/languagetabs.mdx
  demo/docs/customization/styling.mdx
  demo/src/css/custom.css
  packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeSnippets/languages.ts
Labels: bug, v4.0.0

#957 Add missing security schemes component
  packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/Request/_Request.scss
  packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/index.tsx
Labels: bug

#958 render default value as string literal instead of markdown
  packages/docusaurus-plugin-openapi-docs/src/markdown/createSchema.ts
  packages/docusaurus-theme-openapi-docs/src/theme/ParamsItem/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/SchemaItem/index.tsx
  yarn.lock
Labels: bug

#960 Fix deprecation notice
  packages/docusaurus-plugin-openapi-docs/src/markdown/createDeprecationNotice.ts
Labels: bug, v4.0.0

#963 Add support for custom sidebar DocItem generators supporting customisation
  README.md
  packages/docusaurus-plugin-openapi-docs/README.md
  packages/docusaurus-plugin-openapi-docs/src/options.ts
  packages/docusaurus-plugin-openapi-docs/src/sidebars/index.ts
  packages/docusaurus-plugin-openapi-docs/src/types.ts
Labels: enhancement, v4.0.0
