Repository PaloAltoNetworks/docusaurus-openapi-docs, pull requests merged in 2024-12, with the labels that each got.

#1031 Remove unused global selector
  packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/ApiCodeBlock/Line/_Line.scss
Labels: v4.0.0

#1033 Address HTML minifier warnings caused by malformed MDX and HTML
  packages/docusaurus-plugin-openapi-docs/src/markdown/createAuthentication.ts
  packages/docusaurus-plugin-openapi-docs/src/markdown/createTermsOfService.ts
Labels: bug, v4.0.0

#1039 Reintroduce password type to auth inputs
  packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/Authorization/index.tsx
Labels: enhancement, v4.0.0

#1040 Support discriminator with no parent/shared properties
  demo/examples/tests/discriminator.yaml
  packages/docusaurus-theme-openapi-docs/src/theme/Schema/index.tsx
Labels: bug, v4.0.0

#1050 Hide credentials from generated code snippets
  packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeSnippets/index.tsx
  packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/buildPostmanRequest.ts
Labels: enhancement, v4.0.0

#1051 Handle case where auth options are combined
  packages/docusaurus-theme-openapi-docs/src/theme/ApiExplorer/CodeSnippets/index.tsx
Labels: v4.0.0
