Repository PaloAltoNetworks/docusaurus-openapi-docs, pull requests merged in 2025-03, with the labels that each got.

#1105 Prepare release v4.3.6
  CHANGELOG.md
  demo/package.json
  lerna.json
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
Labels: v4.0.0

#1109 Prepare release v4.3.7
  CHANGELOG.md
  demo/package.json
  lerna.json
  packages/docusaurus-plugin-openapi-docs/package.json
  packages/docusaurus-theme-openapi-docs/package.json
Labels: bug, v4.0.0

#1117 Add httpbin.org spec to examples
  demo/docusaurus.config.ts
  demo/examples/httpbin.yaml
  demo/sidebars.ts
Labels: enhancement
