Repository PaloAltoNetworks/docusaurus-openapi-docs, pull requests merged in 2025-07, with the labels that each got.

#1190 Add allOf required spec and fix items branch
  demo/examples/tests/allOf.yaml
  packages/docusaurus-theme-openapi-docs/src/theme/Schema/index.tsx
Labels: bug

#1207 docs: explain swizzling DocCard
  demo/docs/customization/doccard.mdx
Labels: documentation

#1200 Improve error handling when spec isn't valid
  packages/docusaurus-plugin-openapi-docs/src/openapi/openapi.ts
Labels: enhancement

#1209 Additional hardening measures for GitHub Actions workflows
  .github/workflows/build-perf.yml
  .github/workflows/deploy-preview.yml
  .github/workflows/release-beta.yaml
  .github/workflows/release.yaml
  .github/workflows/validate.yaml
Labels: chore
